### ISSUE TITLE
Make ynbool a descriptor object

### ISSUE THREAD

**Issue by fpp-gh** [jaseg/python-mpv#13] opened 2016-08-02 08:52 UTC
> I hadn't even noticed there were supposed to be properties, but so much the better, thanks :-)

Well, snide remarks aside, these properties are really nifty, especially the read/write ones, and make for much tighter and cleaner code !

The behaviour of the booleans had me scratching my head for a while though, so I thought I'd document it here in case others wondered too...

In interactive mode under ipython:

In [24]: import mpv
In [25]: m=mpv.MPV(pause=True)
In [26]: m.loadfile('test.avi') # video shown paused
 # as expected:
In [27]: m.pause
Out[27]: True
 # but...
In [28]: print m.pause
yes
 # explicit change:
In [29]: m.pause=False # starts playback as expected
 # and...
In [30]: print m.pause
no
 # try the classic toggle :
In [31]: m.pause = not m.pause
 # fail :
In [32]: m.pause
Out[32]: False
In [33]: print m.pause
no
 # only workaround I've found:
In [34]: m.pause = True if m.pause == 'no' else False
In [35]: m.pause
Out[35]: True
In [36]: print m.pause
yes

Maybe a side effect of running python2 and/or Windows ?

**Comment by jaseg** [comment] 2016-08-02 11:52
hmm, I might have to fix this. ~~I don't think that's a python2 thing~~ ok, this stems from python2 handling truthiness differently. It's fixed now. Seriously, try migrating to python 3, it's much less strange ;)

btw, the yes/no/True/False thing is because of the way the module sticks ynbools into mpv's lua API. If you want True/False, use repr() instead of str() (as print does by default). Both ```print repr(my_mpv.some_ynbool)``` and ```'{!r}'.format(some_ynbool)``` should work. You can also just make it a bool, if you want that: ```print bool(my_mpv.some_ynbool)```.

A more proper fix for that awkward behavior would probably be to rewrite the ynbool-stuff using descriptor objects, but for now it works well enough that it's not worth it to me ;)

**Comment by jaseg** [comment] 2016-08-02 11:54
Side note: With ```__set_name__```, there is some goodness coming to descriptors in Python 3.6. Maybe that will be an incentive to fix this^^

**Comment by fpp-gh** [comment] 2016-08-02 12:21
Again, thanks much for the explanations and fix !

I totally agree there is no urgency to fix this, as it's easy to work around.
I only mentioned it here so it could maybe save someone else some time...

As for Py3, I'm well aware that you're quite right.
It's just that I'm a totally amateur coder, working on personal stuff in my spare time.
I got started with Python 1.5 in the nineties, and changing habits is hard...

But things are definitely changing:
Up to recently I was mostly hearing of essential packages that didn't support Py3,
...and this here is the first time I happen upon a Py3 lib that I absolutely want :-)

**Comment by fpp-gh** [comment] 2016-08-07 15:29
Yet another Python-2 wart, I guess : mpv doesn't seem to accept non-ascii arguments, like in file names...

Am I missing something, or is tinkering needed ? :-)

**Comment by jaseg** [comment] 2016-08-07 17:05
Hmmm...

I just pushed a fix that will at least handle the obvious cases correctly. I.e. on python2 you pass in a unicode string, on python3 you pass in a regular str and it encodes it using python's filesystem encoding. libmpv itself says in ```client.h``` that it will just pass through that stuff, and for now that seems to work well enough.

*However* the rest of libmpv (including the entire lua interface) will use utf-8, disregarding the system encoding. I just fixed the interface to honor this, and you should now be fine as long as you stick in python unicode strings everywhere (for commands and filenames) and the interface should handle this correctly.

The one case where this is still not handled correctly is properties or lua commands that accept filenames. For the latter, just do the filename encoding yourself using ```sys.getfilesystemencoding()```, for the former I might push a fix later.

**Comment by fpp-gh** [comment] 2016-08-07 17:25
Fantastic, will try this right away, thanks very much !
And sorry for hijacking your Sunday :-)

**Comment by fpp-gh** [comment] 2016-08-09 17:16
Is that last paragraph still valid ? 
I don't think I can pass loadfile an already encoded filename:
```python
    def loadfile(self, filename, mode='replace'):
        self.command('loadfile', filename.encode(fs_enc), mode)
```
... and when I pass it an utf-8 unicode, the call fails silently (no error, window doesn't show).
I've been on this for like 2 days and still haven't been able to load a file with accents through mpv.py that way...

But I just found out that:
```python
   m.command("loadfile", fn.encode('utf-8'))
```
works instead (although sys.getfilesystemencoding() is not utf-8) !
Is that what you meant above ?

**Comment by jaseg** [comment] 2016-08-09 21:34
You are right, and I did not express myself clearly. ```loadfile``` and similar functions that accept filenames do the encoding for you. However, if you directly call the lua API with ```command```, you have to do the encoding yourself (since there is no way for ```command``` to know which arguments correspond to file names).

Have you tried passing in a unicode object? I'm on linux, using utf-8 system and file system encoding, so I cannot exactly reproduce your case, but the following works for me:
```python
import mpv
p = mpv.MPV()
p.play(u'/data/jaseg/Downloads/ütf8tést')
```
The lib will already do the encode with the file system encoding internally, you do not need to passed pre-encoded data in.

**Comment by jaseg** [comment] 2016-08-09 21:41
Ooooh, I think I found the issue. On a close read of libmpv's client.h it turns out filenames are only passed through directly on linux, on Windows they're actually expected to be utf-8 encoded. Please try the fix on the "winfilenames" branch ( git checkout origin/winfilenames ) and tell me if it worked.

**Comment by fpp-gh** [comment] 2016-08-10 08:17
Thanks for looking deeper into this, I thought I was going crazy !
I checked and rewrote the parameter passing so many times I wasn't sure I understood right anymore :-)
Now both calls work just fine, thanks !

PS: if you're interested in a demo, I have a ~100 lines script using mpv, mpvlib and mpv.py that I use to compare different encodings of videos. It loads two files and controls both playbacks.
The common event loop and minimalist UI  are in wxPython right now, but can be redone easily in any other toolkit.

**Comment by jaseg** [comment] 2016-08-10 10:30
> Now both calls work just fine, thanks !

Thanks for testing. Do you mean the winfilenames branch with that? If yes I'll merge that one into master.

**Comment by fpp-gh** [comment] 2016-08-10 10:32
Yes, with the winfilenames branch, sorry.

**Comment by jaseg** [comment] 2016-08-10 12:39
Ok, this is now on master, and the winfilenames branch has been deleted.

**Comment by jaseg** [comment] 2017-05-26 12:15
I think I can close this now. The property API has moved on quite a bit with full ```NODE``` support.

**Closed by jaseg** 2017-05-26 12:15 UTC
