### ISSUE TITLE
Cannot run the seek command

### ISSUE THREAD

**Issue by Luni-4** [jaseg/python-mpv#144] opened 2020-11-09 10:05 UTC
I'm on `Ubuntu 20.10` with `python-mpv 0.5.2`. When I try to launch this script: 
```
import mpv

player = mpv.MPV(ytdl=False, osc=True, loglevel="info", log_handler=print)
player.seek("00:01:14.0", "absolute", "exact")
player.play('/path/to/file.mkv')
player.wait_for_playback()
```
I get the following error:

```
Traceback (most recent call last):
  File "test.py", line 5, in <module>
    player.seek("00:01:14.0", "absolute", "exact")
  File "/home/.local/lib/python3.8/site-packages/mpv.py", line 1054, in seek
    self.command('seek', amount, reference, precision)
  File "/home/.local/lib/python3.8/site-packages/mpv.py", line 1041, in command
    _mpv_command(self.handle, (c_char_p*len(args))(*args))
  File "/home/.local/lib/python3.8/site-packages/mpv.py", line 133, in raise_for_ec
    raise ex(ec, *args)
SystemError: ('Error running mpv command', -12, (<MpvHandle object at 0x7fbdef494dc0>, <mpv.c_char_p_Array_5 object at 0x7fbdef1bb4c0>))
```

Am I doing something wrong? Thanks in advance for your help! :)

**Comment by jaseg** [comment] 2020-11-09 13:34
You can't seek before the file is loaded. As an alternative, consider passing [the `start` option](https://mpv.io/manual/master/#options-start) to either the MPV object or to `MPV.loadfile`.

**Comment by Luni-4** [comment] 2020-11-09 13:48
Yep, you're right, I inverted the lines:

```
 import mpv

player = mpv.MPV(ytdl=False, osc=True, loglevel="info", log_handler=print)
player.play('/path/to/file.mkv')
player.seek("00:01:14.0", "absolute", "exact")
player.wait_for_playback()
```
but I get the same error.

Instead, the `start` option inside the `MPV` object works, but unfortunately I need the `seek` function

**Comment by McSinyx** [comment] 2020-11-09 13:58
I think this is the duplicate of GH-79.  Maybe we should have a context manager whose `__enter__` waits for basic properties to initialize and `__exit__` calls `wait_for_playback`, but I'm not sure which mpv properties should be considered as basic.

**Comment by Luni-4** [comment] 2020-11-09 14:03
Thank you @McSinyx! I tried the solution described in the duplicate issue and now it works perfectly! :)

**Closed** 2020-11-22 12:36 UTC
