### ISSUE TITLE
Undefined symbol: mpv_create_client

### ISSUE THREAD

**Issue by DavideSegullo** [jaseg/python-mpv#33] opened 2017-06-06 17:26 UTC
Hi, i'm trying to import "mpv" . But i get the following errors:
```import mpv
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.4/dist-packages/mpv.py", line 319, in <module>
    _handle_func('mpv_create_client',           [c_char_p],                                 MpvHandle, notnull_errcheck)
  File "/usr/local/lib/python3.4/dist-packages/mpv.py", line 280, in _handle_func
    func = getattr(backend, name)
  File "/usr/lib/python3.4/ctypes/__init__.py", line 364, in __getattr__
    func = self.__getitem__(name)
  File "/usr/lib/python3.4/ctypes/__init__.py", line 369, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: /usr/lib/arm-linux-gnueabihf/libmpv.so.1: undefined symbol: mpv_create_client
```
How can i solve this problem? 
Tnx

**Comment by jaseg** [comment] 2017-06-06 18:20
What version of libmpv are you using? Ask your package manager for this.

**Comment by DavideSegullo** [comment] 2017-06-06 18:28
libmpv-dev/stable,now 0.6.2-2 armhf [installed]
libmpv1/stable,now 0.6.2-2 armhf [installed, automatic]

I'm working on Raspbian jessie

**Comment by jaseg** [comment] 2017-06-06 19:07
Ok. The problem is that your libmpv is really, really old. You can either try getting a current libmpv (e.g. by compiling from source) or use a really, really old version of this python module.

**Comment by DavideSegullo** [comment] 2017-06-06 19:11
I'll try to do it and tell you if it works. Thanks :)

**Comment by DavideSegullo** [comment] 2017-06-06 19:12
Where can I find the source?

**Comment by jaseg** [comment] 2017-06-06 19:17
https://github.com/mpv-player/mpv and https://mpv.io

**Comment by jaseg** [comment] 2017-06-06 19:41
BTW, you *can* cross-compile mpv on your normal computer (laptop/desktop). You don't have to do that on your Pi. You normal computer will be like infinitely faster!

**Comment by DavideSegullo** [comment] 2017-06-06 19:46
How can i do that? Sorry i'm newbie

**Comment by jaseg** [comment] 2017-06-06 19:51
You're in for a treat then ;)

Probably start [here](https://github.com/mpv-player/mpv-build#generic-instructions).

**Comment by DavideSegullo** [comment] 2017-06-06 19:53
I have already used this guide, but install that old version :/

**Comment by jaseg** [comment] 2017-06-06 19:57
Uninstall ```libmpv``` using your package manager (```libmpv-dev``` and ```libmpv1```), and look whether there's anything looking like it might be a libmpv in ```/usr/local/lib```

**Comment by DavideSegullo** [comment] 2017-06-06 21:19
Inside /usr/local/lib there are three directory (pypy2.7,python2.7 and python3.4).  I'm using python 3, so inside /usr/local/lib/python3.4/dist-packages there is only you're script "mpv.py".

**Comment by jaseg** [comment] 2017-06-06 21:22
If libmpv is installed correctly from the ```mpv-build``` script, there should be something named similar to ```libmpv.so``` in ```/usr/lib```, ```/usr/lib/mpv```, ```/usr/local/lib``` or ```/usr/local/lib/libmpv``` or similar.

**Comment by DavideSegullo** [comment] 2017-06-06 21:35
There isn't any file named "libmpv.so". 

I used the following command:
sudo dpkg -i mpv_2017.06.03.fdd75f9_armhf.deb

The "mpv" command works

**Comment by jaseg** [comment] 2017-06-06 21:41
```libmpv``` and ```mpv``` are two different packages. Try finding a ```libmpv``` package instead.

**Comment by DavideSegullo** [comment] 2017-06-06 21:46
There is only one "libmpv" and it's inside the installation folder.
here:
/home/pi/Desktop/mpv-build/mpv/libmpv

**Comment by jaseg** [comment] 2017-06-06 22:15
Is there a ```.so``` file somewhere in there?

**Comment by jaseg** [comment] 2017-06-06 22:15
Oh, I see, and did you do what is described [here](https://github.com/mpv-player/mpv-build#building-libmpv)?

**Comment by DavideSegullo** [comment] 2017-06-07 05:53
There aren't any .so files.
I followed the "Istructions for debian and ubuntu"

**Comment by jaseg** [comment] 2017-06-07 08:20
Did you follow [this](https://github.com/mpv-player/mpv-build#building-libmpv)?

**Comment by DavideSegullo** [comment] 2017-06-07 09:00
No :/ . Did i need to rebuild it?

**Comment by jaseg** [comment] 2017-06-07 09:08
Yup

**Comment by DavideSegullo** [comment] 2017-06-07 09:08
Ok, thank you. I'll do it

**Comment by DavideSegullo** [comment] 2017-06-07 10:11
During the compiling phase i get the following errors:
src/libavcodec/wmadec.c: In function ‘wma_decode_init’:
src/libavcodec/wmadec.c:128:1: internal compiler error: Errore di segmentazione
 }
 ^
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-4.9/README.Bugs> for instructions.
CC	libavcodec/wmalosslessdec.o
The bug is not reproducible, so it is likely a hardware or OS problem.
/home/pi/Desktop/mpv-build/ffmpeg/ffbuild/common.mak:59: set di istruzioni per l'obiettivo "libavcodec/wmadec.o" non riuscito
make[2]: *** [libavcodec/wmadec.o] Errore 1
make[2]: *** Attesa per i processi non terminati....
make[2]: uscita dalla directory "/home/pi/Desktop/mpv-build/ffmpeg_build"
debian/rules:63: set di istruzioni per l'obiettivo "ffmpeg_build" non riuscito
make[1]: *** [ffmpeg_build] Errore 2
make[1]: uscita dalla directory "/home/pi/Desktop/mpv-build"
debian/rules:23: set di istruzioni per l'obiettivo "build" non riuscito
make: *** [build] Errore 2
dpkg-buildpackage: error: debian/rules build gave error exit status 2

**Comment by jaseg** [comment] 2017-06-07 10:18
Did you run ```./clean``` as it says in the ```README```?

**Comment by DavideSegullo** [comment] 2017-06-07 13:35
Yes, i'll try it again

**Comment by McSinyx** [comment] 2017-06-07 14:02
`apt` will put `libmpv.so` in `/usr/lib/i386-linux-gnu/libmpv.so.1` (provided by `libmpv1`). Not sure where it'd be if installed from source.

**Comment by DavideSegullo** [comment] 2017-06-07 15:47
Now i get the following errors:
[458/460] Linking build/mpv
[459/460] Linking build/libmpv.so
/usr/lib/gcc/arm-linux-gnueabihf/4.9/../../../arm-linux-gnueabihf/Scrt1.o: nella funzione "_start":
/build/glibc-lGD2lt/glibc-2.19/csu/../ports/sysdeps/arm/start.S:128: riferimento non definito a "main"
collect2: error: ld returned 1 exit status

Waf: Leaving directory `/home/pi/Desktop/mpv-build/mpv/build'
Build failed
 -> task in 'mpv' failed with exit status 1 (run with -v to display more information)
debian/rules:70: set di istruzioni per l'obiettivo "override_dh_auto_build" non riuscito
make[1]: *** [override_dh_auto_build] Errore 1
make[1]: uscita dalla directory "/home/pi/Desktop/mpv-build"
debian/rules:23: set di istruzioni per l'obiettivo "build" non riuscito
make: *** [build] Errore 2
dpkg-buildpackage: error: debian/rules build gave error exit status 2

**Comment by DavideSegullo** [comment] 2017-06-08 09:31
I've solved the compilation problems.
Now inside "/usr/local/lib" there are three files:
- libmpv.so
- libmpv.so.1
- libmpv.so.1.24.0

If i try to import "mpv" from python3 i get the following errors:
`Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.4/dist-packages/mpv.py", line 49, in <module>
    backend = CDLL(sofile)
  File "/usr/lib/python3.4/ctypes/__init__.py", line 351, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libmpv.so.1: cannot open shared object file: No such file or directory
`
Do you know how I can solve it?
Thanks for your help

**Comment by jaseg** [comment] 2017-06-08 09:52
Ah, that sounds better. ```python-mpv``` will search your system library path for ```libmpv.so```. On many linuxes, by default ```/usr/local/lib``` is not part of that. The easiest way to fix this is to run your python  interpreter with the ```LD_LIBRARY_PATH``` environment variable set appropriately like this: ```env LD_LIBRARY_PATH=/usr/local/lib python my_script.py```.

**Comment by DavideSegullo** [comment] 2017-06-08 09:55
Oh perfect! It works now :D . Thank you !

**Comment by jaseg** [comment] 2017-06-08 09:59
Hah! finally :D I'll close this now, then.

**Closed by jaseg** 2017-06-08 09:59 UTC
